version: '3.2'
services:

  db:
    container_name: test-task-db
    build: ./docker/container/pgsql
    restart: always
    image: postgres
    ports:
      - "5432:5432"
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    volumes:
        - ./temp/postgres:/var/lib/postgresql/data
        - ./db/dump.sql:/docker-entrypoint-initdb.d/dump.sql

